# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Users/Aneesh/.gradle/jdks/eclipse_adoptium-25-amd64-windows.2

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.4

# Mod Properties
mod_version=1.0.3
maven_group=com.example
archives_base_name=autofisher

# Dependencies
fabric_version=0.158.0+26.2
